### ISSUE TITLE
MySQL server error

### ISSUE THREAD

**Issue by PetrJoe** [maesterzak/DjangoVercel#3]
I tried using Remote MySQL server for my Django project on vercel but having issue with installation

Can tou you do the tutorial about this or can you find a solution and create a video about it

**Comment by maesterzak** [comment]
Hello Akanmu01, am not sure I can be of much help here. All my past django projects have always used a postgreSQL database. Check out the link below to learn how to add one to your django website.
https://www.devmaesters.com/blog/31
